### ISSUE TITLE
Create a .NET Standard 2.0 NuGet package

### ISSUE THREAD

**Issue by loop-evgeny** [fsprojects/FSharp.Collections.ParallelSeq#15]
### Description

There is no .NET Core 2.0 version of the NuGet package.

### Repro steps

Build a .NET Core 2.0 project that references FSharp.Collections.ParallelSeq.

### Expected behavior

No warnings.

### Actual behavior

A build warning is logged:

    warning NU1701: Package 'FSharp.Collections.ParallelSeq 1.0.2' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.0'. This package may not be fully compatible with your project.

### Related information 

* Windows 7, Linux
* NuGet package 1.0.2
* .NET Core 2.0

**Comment by ChrSteinert** [comment]
Don't you want to leave that open until the actual NuGet package is out there?

**Comment by jamessdixon** [comment]
IDK - Don didn't seem to give a preference either way - you have an opinion?

**Comment by ChrSteinert** [comment]
Let's have it. At least as a reminder that the NuGet still needs to be done (increment version etc.)

**Comment by jamessdixon** [comment]
are you planning to set up CI/CD for this?  If not, I can do push to nuget manually until I get to setting it up.  Don said you might be doing CI/CD for a bunch of ones?

**Comment by ChrSteinert** [comment]
Did he? 😄 
I'd aimed to focus on migrating to .NET Standard at least. But for now, no I do not plan to have CD anytime soon. I would highly appreciate if you manually upload the NuGet.
What version number are you going to use?

**Comment by jamessdixon** [comment]
I'll set up the CD then.  Not sure about the version number - I was going increment minor unless you have an opinion

**Comment by ChrSteinert** [comment]
1.1.0 Sounds fine 👍

**Comment by ChrSteinert** [comment]
@jamessdixon Can I lend you a hand?

**Comment by jamessdixon** [comment]
It's on my weekend project list

**Comment by ChrSteinert** [comment]
Cool, take your time!

**Comment by jamessdixon** [comment]
So I went to create the package (and add in PAKET)
The 1st line of the build.fsx script is this:
#I @"packages/FAKE/tools/"

But that folder is not in the package folder?

**Comment by ChrSteinert** [comment]
Have you run the build.cmd? It will call NuGet to install FAKE right there 👍

**Comment by jamessdixon** [comment]
I did
no luck
:-/

**Comment by ChrSteinert** [comment]
Works for me. Can you tell me what you did and if there have been any error Messages?

![parallelseq](https://user-images.githubusercontent.com/9868229/36581342-b9bca7dc-186c-11e8-88cf-359ed4569d5b.gif)

**Comment by jamessdixon** [comment]
![image](https://user-images.githubusercontent.com/1394644/36646584-4ffebdee-1a47-11e8-85a0-8c61c55b53f7.png)

**Comment by jamessdixon** [comment]
I don't get to that point.  I am using the Visual Studio 2017 Dev Cmd Shell
I'll try Code, like you have

**Comment by jamessdixon** [comment]
if you already have the nuget package, want to dropbox it to me and I can put it up on nuget - just to get it out there?

**Comment by ChrSteinert** [comment]
I just pushed the package, so that it is out. Now we have lots of time to fix your local build! ;)

https://www.nuget.org/packages/FSharp.Collections.ParallelSeq/1.1.0
I guess we can now close this.

**Comment by jamessdixon** [comment]
So I found the problem
The nuget.config file in source is wrong
it is related to this issue:  https://github.com/fsharp/FAKE/issues/1416
When I updated the nuget.config to what Stephen said, nuget brought down FAKE and it worked
I'll update source to help those without a general nuget.config file on their machine

**Comment by jamessdixon** [comment]
So when I run a local build, I see
![image](https://user-images.githubusercontent.com/1394644/36835464-4dca87d2-1d04-11e8-851f-c1707c9b48db.png)

 D:\Code\Fake is harded coded into the script somwhere ?

**Comment by ChrSteinert** [comment]
`D:\Code\Fake` is the Location of the sources files on the machine that build the binary. So no relevancy for the execution of the binary itself. 

The "real" error is above. Can you please post the full output?

**Comment by jamessdixon** [comment]
Checking Paket version (downloading latest stable)...
Paket.exe 5.148.0 is up to date.
Paket version 5.148.0
Skipping resolver for group Main since it is already up-to-date
C:\Git\FSharp.Collections.ParallelSeq\paket.lock is already up-to-date
Installing into projects:
 - Creating model and downloading packages.
Performance:
 - Disk IO: 14 milliseconds
 - Runtime: 1 second
Building project with version: LocalBuild
Shortened DependencyGraph for Target RunTests:
<== RunTests
   <== Build
      <== AssemblyInfo
         <== Clean

The running order is:
  - Clean
  - AssemblyInfo
  - Build
  - RunTests
Running build with 1 worker
Starting Target: Clean
Deleting contents of bin
Deleting contents of temp
Finished Target: Clean
Starting Target: AssemblyInfo (==> Clean)
Created AssemblyInfo file "src/FSharp.Collections.ParallelSeq/AssemblyInfo.fs".
Finished Target: AssemblyInfo
Starting Target: Build (==> AssemblyInfo)
dotnet "build" --configuration Release
'"dotnet-build"' is not recognized as an internal or external command,
operable program or batch file.
Running build failed.
Error:
System.Exception: Build failed on "build" --configuration Release
   at Fake.DotNetCli.Build@224-3.Invoke(String message) in D:\code\fake\src\app\FakeLib\DotNetCLIHelper.fs:line 224
   at Fake.DotNetCli.Build(FSharpFunc`2 setBuildParams) in D:\code\fake\src\app\FakeLib\DotNetCLIHelper.fs:line 224
   at FSI_0005.Build.clo@89-6.Invoke(Unit _arg4)
   at Fake.TargetHelper.runSingleTarget(TargetTemplate`1 target) in D:\code\fake\src\app\FakeLib\TargetHelper.fs:line 626

---------------------------------------------------------------------
Build Time Report
---------------------------------------------------------------------
Target         Duration
------         --------
Clean          00:00:00.0039104
AssemblyInfo   00:00:00.0495508
Build          Failure
Total:         00:00:00.5169714
---------------------------------------------------------------------
Status:        Failure
---------------------------------------------------------------------
---------------------------------------------------------------------
  1) System.Exception: Build failed on "build" --configuration Release
   at Fake.DotNetCli.Build@224-3.Invoke(String message) in D:\code\fake\src\app\FakeLib\DotNetCLIHelper.fs:line 224
   at Fake.DotNetCli.Build(FSharpFunc`2 setBuildParams) in D:\code\fake\src\app\FakeLib\DotNetCLIHelper.fs:line 224
   at FSI_0005.Build.clo@89-6.Invoke(Unit _arg4)
   at Fake.TargetHelper.runSingleTarget(TargetTemplate`1 target) in D:\code\fake\src\app\FakeLib\TargetHelper.fs:line 626
---------------------------------------------------------------------

**Comment by ChrSteinert** [comment]
This Looks like you are missing the .NET Core SDK. Go fetch it here: https://www.microsoft.com/net/download/

**Comment by jamessdixon** [comment]
I have that installed
[image: Inline image 1]

Maybe not on my PATH?

On Thu, Mar 1, 2018 at 4:14 AM, Christian Steinert <notifications@github.com

**Comment by ChrSteinert** [comment]
Just try to get the new one from the page above!

**Comment by jamessdixon** [comment]
I did :-)

On Thu, Mar 1, 2018 at 4:25 AM, Christian Steinert <notifications@github.com

**Comment by jamessdixon** [comment]
[image: Inline image 1]

just doesn't like it from the build script I guess

**Comment by ChrSteinert** [comment]
Can you do a clean clone of the repo and try again?

**Comment by jamessdixon** [comment]
same error


On Thu, Mar 1, 2018 at 4:34 AM, Christian Steinert <notifications@github.com
